In [1]:
import numpy as np

In [2]:
#MATHEMATICAL OPERATION USING NUMPY

In [5]:
ar1=np.arange(1,10).reshape(3,3)
ar2=np.arange(1,10).reshape(3,3)
print(ar1)
print(ar2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [6]:
ar1+ar2

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [7]:
np.add(ar1,ar2)

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [8]:
ar1-ar2

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [9]:
np.subtract(ar1,ar2)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [10]:
ar1/ar2

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [12]:
np.divide(ar1,ar2)

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [13]:
ar1 * ar2

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]])

In [14]:
np.multiply(ar1,ar2)

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]])

In [15]:
ar1@ar2

array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]])

In [16]:
ar1.dot(ar2)

array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]])

In [18]:
ar1.max()

9

ar1.argmax()

In [19]:
ar1.argmax()

8

In [20]:
ar1.max(axis=0)

array([7, 8, 9])

In [21]:
ar1.max(axis=1)

array([3, 6, 9])

In [22]:
ar1.min()


1

In [23]:
ar1.argmin()

0

In [24]:
ar1.min(axis=0)

array([1, 2, 3])

In [25]:
ar1.min(axis=1)

array([1, 4, 7])

In [26]:
ar1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [27]:
np.sum(ar1)

45

In [28]:
np.sum(ar1,axis=0)

array([12, 15, 18])

In [29]:
np.sum(ar1,axis=1)

array([ 6, 15, 24])

In [30]:
np.mean(ar1)

5.0

In [31]:
np.mean(ar1,axis=1)

array([2., 5., 8.])

In [32]:
np.mean(ar1,axis=0)

array([4., 5., 6.])

In [33]:
np.sqrt(ar1) #square root

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 2.82842712, 3.        ]])

In [34]:
np.std(ar1) #standard deviation

2.581988897471611

In [35]:
np.exp(ar1)

array([[2.71828183e+00, 7.38905610e+00, 2.00855369e+01],
       [5.45981500e+01, 1.48413159e+02, 4.03428793e+02],
       [1.09663316e+03, 2.98095799e+03, 8.10308393e+03]])

In [36]:
np.log(ar1) #natural log

array([[0.        , 0.69314718, 1.09861229],
       [1.38629436, 1.60943791, 1.79175947],
       [1.94591015, 2.07944154, 2.19722458]])

In [37]:
np.log10(ar1)

array([[0.        , 0.30103   , 0.47712125],
       [0.60205999, 0.69897   , 0.77815125],
       [0.84509804, 0.90308999, 0.95424251]])

In [39]:
np.log(ar1)

array([[0.        , 0.69314718, 1.09861229],
       [1.38629436, 1.60943791, 1.79175947],
       [1.94591015, 2.07944154, 2.19722458]])