In [5]:
import numpy as np

In [3]:
#numpy_heading


In [16]:
#arrange()

#np.arrange(start,ends,steps)
import numpy as np
ar1=np.arange(1,13)
print(ar1)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [12]:
#linspace()

np.linspace(1,5,4)

array([1.        , 2.33333333, 3.66666667, 5.        ])

In [17]:
#reshape

ar2=ar1.reshape(2,6)
print(ar2)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


In [19]:
ar22=ar1.reshape(3,4)
print(ar22)


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [20]:
ar23=ar1.reshape(2,3,2)
print(ar23)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [21]:
np.arange(1,13).reshape(2,6)

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [22]:
#ravel

ar2.ravel()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [23]:
#flatten

ar2.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [25]:
#transpose

ar2.transpose()

array([[ 1,  7],
       [ 2,  8],
       [ 3,  9],
       [ 4, 10],
       [ 5, 11],
       [ 6, 12]])

In [26]:
ar2.T

array([[ 1,  7],
       [ 2,  8],
       [ 3,  9],
       [ 4, 10],
       [ 5, 11],
       [ 6, 12]])