In [1]:
import numpy as np

In [2]:
#PYTHON NUMPY ARRAY CONCATINATION AND SPLIT

In [6]:
ar1=np.arange(1,17).reshape(4,4)
print(ar1)
ar2=np.arange(17,33).reshape(4,4)
print(ar2)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
[[17 18 19 20]
 [21 22 23 24]
 [25 26 27 28]
 [29 30 31 32]]


In [7]:
#list concatenate

l1=[1,2,3,4]
l2=[4,5,6,7]
l1+l2

[1, 2, 3, 4, 4, 5, 6, 7]

In [10]:
#array concatenate column wise

np.concatenate((ar1,ar2))

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24],
       [25, 26, 27, 28],
       [29, 30, 31, 32]])

In [12]:
#array concatenate row wise

np.concatenate((ar1,ar2),axis=1)

array([[ 1,  2,  3,  4, 17, 18, 19, 20],
       [ 5,  6,  7,  8, 21, 22, 23, 24],
       [ 9, 10, 11, 12, 25, 26, 27, 28],
       [13, 14, 15, 16, 29, 30, 31, 32]])

In [13]:
np.vstack((ar1,ar2))

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24],
       [25, 26, 27, 28],
       [29, 30, 31, 32]])

In [14]:
np.hstack((ar1,ar2))

array([[ 1,  2,  3,  4, 17, 18, 19, 20],
       [ 5,  6,  7,  8, 21, 22, 23, 24],
       [ 9, 10, 11, 12, 25, 26, 27, 28],
       [13, 14, 15, 16, 29, 30, 31, 32]])

In [15]:
ar3=np.arange(33,49).reshape(4,4)

In [16]:
np.hstack((ar1,ar2,ar3))

array([[ 1,  2,  3,  4, 17, 18, 19, 20, 33, 34, 35, 36],
       [ 5,  6,  7,  8, 21, 22, 23, 24, 37, 38, 39, 40],
       [ 9, 10, 11, 12, 25, 26, 27, 28, 41, 42, 43, 44],
       [13, 14, 15, 16, 29, 30, 31, 32, 45, 46, 47, 48]])

In [17]:
#to split

In [18]:
ar1

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [24]:
l=np.split(ar1,4)
print(l)

[array([[1, 2, 3, 4]]), array([[5, 6, 7, 8]]), array([[ 9, 10, 11, 12]]), array([[13, 14, 15, 16]])]


In [25]:
type(l)

list

In [26]:
l[0]

array([[1, 2, 3, 4]])

In [27]:
np.split(ar1,2,axis=1)

[array([[ 1,  2],
        [ 5,  6],
        [ 9, 10],
        [13, 14]]),
 array([[ 3,  4],
        [ 7,  8],
        [11, 12],
        [15, 16]])]

In [28]:
d1=np.array([4,7,3,1,9])

In [29]:
np.split(d1,[1,3])

[array([4]), array([7, 3]), array([1, 9])]