In [3]:
import numpy as np

In [4]:
ar=np.array([1,2,3,4])
print(ar)

[1 2 3 4]


In [5]:
type(ar)

numpy.ndarray

In [6]:
ar.ndim

1

In [8]:
 ar2=np.array([[1,2,3,4],[5,6,7,8]])
print(ar2)

[[1 2 3 4]
 [5 6 7 8]]


In [10]:
ar2.ndim

2

In [11]:
ar2.size

8

In [12]:
ar2.shape

(2, 4)

In [13]:
ar2.dtype

dtype('int32')