In [1]:
import numpy as np

In [2]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [4]:
mx1=np.ones((3,4))
print(mx1)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [5]:
mx2=np.ones((3,4),dtype=int)
print(mx2)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [6]:
mx0=np.zeros((5,8))
print(mx0)

[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]


In [7]:
mx0=np.zeros((5,8),dtype=bool)
print(mx0)

[[False False False False False False False False]
 [False False False False False False False False]
 [False False False False False False False False]
 [False False False False False False False False]
 [False False False False False False False False]]


In [9]:
mx0=np.zeros((5,8),dtype=str)
print(mx0)

[['' '' '' '' '' '' '' '']
 ['' '' '' '' '' '' '' '']
 ['' '' '' '' '' '' '' '']
 ['' '' '' '' '' '' '' '']
 ['' '' '' '' '' '' '' '']]


In [10]:
mx0=np.ones((5,8),dtype=bool)
print(mx0)

[[ True  True  True  True  True  True  True  True]
 [ True  True  True  True  True  True  True  True]
 [ True  True  True  True  True  True  True  True]
 [ True  True  True  True  True  True  True  True]
 [ True  True  True  True  True  True  True  True]]


In [13]:
mpemty=np.empty((4,3))
print(mpemty)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
